support Socket.getopts/2
mtrudel/thousand_island pull request #11
Opened 2022-01-31 17:52 UTC by ewildgoose

We already have support for Socket.setopts/2, so also add support
for getopts/2 to read socket options

Note: also correcting the type specifications for {:error, error}
results, which are defined as being Posix error results in general,
however, the SSL app defines it's errors as any(), so we go
with the widest definition

2022-01-31 19:34 UTC, mtrudel commented
Thanks for the PR! Looks good; just waiting on CI to see if dialyzer turns up anything.

2022-01-31 19:35 UTC, mtrudel commented
CI is failing on formatting. Looks like whatever is causing your format diffs on #12 is happening for you here as well.

2022-01-31 19:36 UTC, mtrudel commented
FWIW there's nothing fancy about CI's formatting check. See https://github.com/mtrudel/thousand_island/blob/main/.github/workflows/elixir.yml#L46-L47 for details.

2022-02-01 11:54 UTC, ewildgoose commented
I've re-created this patch. I think the issue was an interaction between this and #11 before. One of my lines was longer than 100 chars or something and it was wrapped in #11. However, I'm having trouble not having the two patches relate to each other, so grateful if you could at least commit #11 as this makes everything else easier to read. However, I think this should pass tests now?

2022-02-01 15:30 UTC, mtrudel requested changes
One inline question + merge conflicts to resolve, then this should be ready to go.

2022-02-01 15:30 UTC, mtrudel commented on lib/thousand_island/transport.ex
> +              {:ok, socket_set_options()} | {:error, String.t()}
Should this be socket_get_options?

2022-02-01 17:26 UTC, ewildgoose commented on lib/thousand_island/transport.ex
> +              {:ok, socket_set_options()} | {:error, String.t()}
I don't think so?

Explaining in plain to avoid confusion:

* Input param is a "get_options" type
* Return param is from the "set_options" type

I guess intuitively this makes sense as what you getopts(), can be fed right back into setopts()

Did I get the spec right above??

2022-02-01 17:31 UTC, ewildgoose commented
Merge conflict resolved

2022-02-03 21:14 UTC, mtrudel commented on lib/thousand_island/transport.ex
> +              {:ok, socket_set_options()} | {:error, String.t()}
I think so. Dialyzer seems to agree, so we're good here.

2022-02-03 21:14 UTC, merged

2022-02-03 21:14 UTC, mtrudel commented
Thanks for the PR!