Add `read_timeout`
mtrudel/thousand_island pull request #16
Opened 2022-05-12 07:38 UTC by moogle19

I added the `read_timeout` as mentioned in #15 .

The `read_timeout` is initialized during `ThousandIsland.start_link/1` and defaults to `:infinity`.
If no explicit timeouts are specified (either in the return values of the callbacks for async or as option on `recv/3` for sync calls) the `read_timeout` value is used.

I added tests to check both cases and one test to validate the priority of the timeouts.

I also tweaked the typespecs for the the `transport_options` and `ThousandIsland.start_link/1` a bit.

2022-05-12 07:58 UTC, moogle19 commented
Not sure why the dialyzer failed for `:inet.inet_backend()` in some tests, since it is also in the `:gen_tcp.listen` typespec (https://www.erlang.org/doc/man/gen_tcp.html#listen-2). But since it also states that it is a temporary option which will be removed in the docs (https://www.erlang.org/doc/man/inet.html#type-inet_backend) I just removed it for now from the typespec.

2022-05-13 16:51 UTC, mtrudel requested changes
Minor typesepc optimization but looks great!

2022-05-13 16:51 UTC, mtrudel commented on lib/thousand_island.ex
> +          | {:error, {:already_started, pid()} | {:shutdown, term()} | term()}
Is this expressible by using a builtin type spec, maybe https://hexdocs.pm/elixir/1.12/Supervisor.html#t:on_start/0?

2022-05-13 17:39 UTC, moogle19 commented on lib/thousand_island.ex
> +          | {:error, {:already_started, pid()} | {:shutdown, term()} | term()}
I just took a look at the possible return values for the specific implementation and it should always return `{:ok, pid()}` or raise. 
`ThousandIsland.start_link/1` always calls `Server.start_link/1` which then calls `Supervisor.start_link/2` and the `init/1` callback for `Server` call `Supervisor.init/2` which always returns `{:ok, tuple()}`.

That means `{:ok, pid()}` would (currently) be the only valid response type for `ThousandIsland.start_link`. But since this could change in the future I am not quite sure if only using that would be a good idea.

`Supervisor.on_start/0` also seems fine.

2022-05-13 18:47 UTC, mtrudel commented
Looks great! Thanks for the PR!

2022-05-13 18:48 UTC, merged

2022-05-13 18:51 UTC, mtrudel commented
Published as 0.5.8