Rewrite the graphical diagram using MermaidJS
mtrudel/thousand_island pull request #31
Opened 2022-12-17 00:58 UTC by sdball

GitHub allows writing MermaidJS diagrams in READMEs so this may be a nicer way to present the process diagram. MermaidJS has an ER diagram type as well which is arguably a more accurate way to describe the model here, but I personally find the flowchart type to be more generally readable.

<img width="954" alt="image" src="https://user-images.githubusercontent.com/45837/208214602-05f7d68d-a1fd-43ac-9bdb-315302e7ab07.png">

2022-12-17 02:31 UTC, ryanwinchester commented
This is cool, and a nice feature for github.

However, NGL, I like the text graphics since it visually works _everywhere_.

2022-12-17 03:24 UTC, sdball commented
Yeah that’s fair. The mermaid diagram is _readable_ but not visual from text editors.

2022-12-17 17:59 UTC, mtrudel requested changes
I like this! Small tidy suggestion pending

2022-12-17 17:59 UTC, mtrudel commented on README.md
> +  AcceptorPoolSupervisor--n-->AcceptorSupervisor
```suggestion
  AcceptorPoolSupervisor--1...n-->AcceptorSupervisor(AcceptorSupervisor: supervisor, rest_for_one)
```

2022-12-17 17:59 UTC, mtrudel commented on README.md
> +  DynamicSupervisor--n-->Handler(Handler: gen_server)
```suggestion
  DynamicSupervisor--1...n-->Handler(Handler: gen_server)
```

2022-12-18 01:18 UTC, sdball commented
I like that change! For reference here it results in the following

![image](https://user-images.githubusercontent.com/45837/208272424-e7659ffd-b009-4a38-a4d2-4d7317d1af9d.png)

2022-12-18 01:20 UTC, ryanwinchester commented
> I like that change! For reference here it results in the following

Or see it at https://github.com/mtrudel/thousand_island/blob/2937161171efab47c5cc5c130be9b72da4f31251/README.md

2022-12-18 01:53 UTC, sdball commented
For sure you can render the file, but for visual feedback it's kinda nice to have it inline.

2022-12-18 18:42 UTC, merged

2022-12-18 18:42 UTC, mtrudel commented
Thanks for the PR!