WIP: Pulling the signatures up from OTP from peer_info/1, local_info/1
mtrudel/thousand_island pull request #67
Opened 2023-06-13 18:00 UTC by asakura

According to conversation in a review comment at https://github.com/mtrudel/bandit/pull/162

2023-06-13 18:01 UTC, asakura commented on lib/thousand_island/handler.ex
> +        {:ok, {ip, port}} = server_config.transport_module.peer_info(raw_socket)
Should be an exception be raised if non `:ok` tuple returned?

2023-06-13 18:02 UTC, asakura commented on lib/thousand_island/transports/ssl.ex
> -      case :ssl.peercert(socket) do
Do you have a preference on how to name a new callback for retrieving peer's certificate? `peer_cert/1`?

2023-06-13 18:11 UTC, mtrudel commented on lib/thousand_island/handler.ex
> +        {:ok, {ip, port}} = server_config.transport_module.peer_info(raw_socket)
I think so. Something along the lines of 'remote end closed the connection before we could initialize it' or something. 

We should probably DRY this up and add it to all the places where we grab peer_info

2023-06-13 18:14 UTC, mtrudel commented on lib/thousand_island/transports/ssl.ex
> -      case :ssl.peercert(socket) do
Why don't we just bring all the names in line with those in the lower libraries? We're changing the signatures for them anyway, so why don't we just go with `peername`, `sockname`, `peercert`?

2023-06-13 18:16 UTC, asakura commented on lib/thousand_island/transports/ssl.ex
> -      case :ssl.peercert(socket) do
I don't see a reason not to do :)

2023-06-14 11:11 UTC, ryanwinchester commented on lib/thousand_island/transports/ssl.ex
> -      case :ssl.peercert(socket) do
But then you're mixing naming conventions. It's a thing people make fun of PHP for.

What if you kept the same name as the lower libraries but in the existing style/convention like `peer_name`, `sock_name`, and `peer_cert`?

2023-06-15 16:31 UTC, asakura commented on lib/thousand_island/handler.ex
> +        socket = ThousandIsland.Socket.attach_span(socket, connection_span)
I don't really like attaching span to a Socket struct after, because that changes type of Socket struct: span is nil or Telemetry.t(). Dialyzer ignores that, but Gradient start barking on function from Socket module because they require to be non-nil.

@mtrudel What do you think?

2023-06-15 16:55 UTC, mtrudel commented on lib/thousand_island/handler.ex
> +        socket = ThousandIsland.Socket.attach_span(socket, connection_span)
Yeah, I think this is why I reached into the transport_module directly to build the peer info in the first place. I think that approach makes more sense unless there's a reason it needs to be this way?

2023-06-15 16:57 UTC, mtrudel commented
Other than the one issue above is this good to go now? We'll want to get this and https://github.com/mtrudel/bandit/pull/167 over in the same moment, with version bumps as appropriate.

2023-06-15 17:34 UTC, asakura commented on lib/thousand_island/handler.ex
> +        socket = ThousandIsland.Socket.attach_span(socket, connection_span)
That was the reason - termination:
```elixir
...
            {:error, reason} ->
              throw({:stop, {:shutdown, {:peername, reason}}, {socket, state}})

...

      # Called if the remote end closed the connection before we could initialize it
      def terminate({:shutdown, {:peername, reason}}, {socket, state}) do
        __MODULE__.handle_error(reason, socket, state)
        do_socket_close(socket, reason)
      end
```

Socket needs to be properly closed (I assume) out the server side as well even if the connection was closed by the client. `do_socket_close/2` expect wrapped socket in to the Socket struct.

```elixir
      defp do_socket_close(%ThousandIsland.Socket{span: span} = socket, reason) do
```

2023-06-15 17:40 UTC, asakura commented on lib/thousand_island/handler.ex
> +        socket = ThousandIsland.Socket.attach_span(socket, connection_span)
Maybe `Socket.new/3` should be responsible for building a span.

2023-06-15 18:13 UTC, asakura commented on lib/thousand_island/handler.ex
> +        socket = ThousandIsland.Socket.attach_span(socket, connection_span)
What do you think of following code? Is there simpler way of doing this:

```elixir
      @impl GenServer
      def handle_info(
            {:thousand_island_ready, raw_socket, server_config, acceptor_span, start_time},
            {nil, state}
          ) do
        case ThousandIsland.Socket.new(raw_socket, server_config, acceptor_span, start_time) do
          {:ok, socket} ->
            ThousandIsland.Telemetry.span_event(socket.span, :ready)

            case ThousandIsland.Socket.handshake(socket) do
              {:ok, socket} -> {:noreply, {socket, state}, {:continue, :handle_connection}}
              {:error, reason} -> {:stop, {:shutdown, {:handshake, reason}}, {socket, state}}
            end

          {:error, reason, socket} ->
            {:stop, {:shutdown, {:peername, reason}}, {socket, state}}
        end
      end

  @spec new(
          ThousandIsland.Transport.socket(),
          ThousandIsland.ServerConfig.t(),
          ThousandIsland.Telemetry.t(),
          non_neg_integer()
        ) :: {:ok, t()} | {:error, :inet.posix(), t()}
  def new(raw_socket, server_config, parent_span, start_time) do
    {error?, span_meta_or_reason} =
      case server_config.transport_module.peername(raw_socket) do
        {:ok, {address, port}} ->
          {false, %{remote_address: address, remote_port: port}}

        {:error, reason} ->
          {true, reason}
      end

    span =
      ThousandIsland.Telemetry.start_child_span(
        parent_span,
        :connection,
        %{monotonic_time: start_time},
        (not error? && span_meta_or_reason) || %{}
      )

    socket = %__MODULE__{
      socket: raw_socket,
      transport_module: server_config.transport_module,
      read_timeout: server_config.read_timeout,
      span: span
    }

    if not error? do
      {:ok, socket}
    else
      {:error, span_meta_or_reason, socket}
    end
  end
```

2023-06-15 20:26 UTC, asakura commented
> Other than the one issue above is this good to go now?

Except that one - none I can recognize.

2023-06-16 16:25 UTC, mtrudel commented on lib/thousand_island/handler.ex
> +        socket = ThousandIsland.Socket.attach_span(socket, connection_span)
The Socket struct was always intended to model the underlying as the user may need to interact with it (that is, it's intended be a user-facing struct first and foremost). To the extent that we use calls against it internally, it's a convenience more than anything. 

If the client closes the connection before we've even had a chance to call `handle_connection`, I don't think we need to worry about signalling the close to the user. It seems to me to be an inconsistent API that might send a `handle_close`callback for a connection that we haven't even called `handle_connection` for yet.

All of which is to say, I don't think we need to be tying ourselves in knots just to accommodate premature closing, certainly not if it makes the code harder to reason about.

2023-06-16 17:12 UTC, asakura commented on lib/thousand_island/handler.ex
> +        socket = ThousandIsland.Socket.attach_span(socket, connection_span)
@mtrudel Oh, great to hear that actually, because some of my concerns has immediately gone. The Socket is user facing abstraction and convenience - check. Before the `handle_connection` is called user cannot spoil pristine state of the handler so no need to call the `handle_close` callback to cleanup. 

But there is one left. If a connection dropped and the GenServer stops right after `peername/1`  returned with error, shouldn't we emit a Telemetry event telling about what happened?

2023-06-16 17:14 UTC, mtrudel commented on lib/thousand_island/handler.ex
> +             acceptor_span, start_time},
As a general style in the library, I prefer to keep pattern matches in function signatures *only* when required for correctness, and to use dot notation in the function body for readability & locality of reference

2023-06-16 17:15 UTC, mtrudel commented on lib/thousand_island/socket.ex
> +      ) do
ibid.

2023-06-16 17:15 UTC, mtrudel requested changes
One last pass on preferring dot access to function signature matching in two places, and I think we're good to go!

2023-06-16 17:21 UTC, asakura commented
https://github.com/mtrudel/bandit/pull/167 is ready only needs adjusting of the TI version

2023-06-16 17:23 UTC, asakura commented on lib/thousand_island/socket.ex
> +      ) do
Reverted

2023-06-16 17:24 UTC, asakura commented on lib/thousand_island/handler.ex
> +             acceptor_span, start_time},
Reverted

2023-06-16 17:27 UTC, mtrudel commented
Yeah this looks great!

2023-06-16 17:31 UTC, mtrudel commented on lib/thousand_island/handler.ex
> +              throw({:stop, {:shutdown, {:premature_conn_closing, reason}}, {raw_socket, state}})
In 6 or so years of full time Elixir this is like the third time I've actually used `throw` LOL

2023-06-16 17:32 UTC, mtrudel commented on lib/thousand_island/handler.ex
> -            {%ThousandIsland.Socket{socket: raw_socket} = socket, state}
Ah shoot one more.

2023-06-16 17:33 UTC, mtrudel commented on lib/thousand_island/handler.ex
> -      defp do_socket_close(socket, reason) do
ibid.

2023-06-16 17:33 UTC, asakura commented on lib/thousand_island/handler.ex
> +              throw({:stop, {:shutdown, {:premature_conn_closing, reason}}, {raw_socket, state}})
You were lucky all this time:

```bash
proprietary_code $ rg throw | wc -l
2506
```

2023-06-16 17:34 UTC, mtrudel commented on lib/thousand_island/handler.ex
> +              throw({:stop, {:shutdown, {:premature_conn_closing, reason}}, {raw_socket, state}})
yowza.

2023-06-16 17:41 UTC, asakura commented on lib/thousand_island/handler.ex
> -            {%ThousandIsland.Socket{socket: raw_socket} = socket, state}
Reverted

2023-06-16 17:41 UTC, asakura commented on lib/thousand_island/handler.ex
> -      defp do_socket_close(socket, reason) do
Reverted

2023-06-16 17:48 UTC, merged